# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEPWVeVCTTV_KGLyJ4KiwykvspTS0NVv
"""

numero1 = []
numero2 = []
base = int(input("INGRESE LA BASE: "))
for i in range(2):
  cantidad = int(input(f"INGRESE LA CANTIDAD DE DIGITOS DEl NUMERO {i+1}: "))
  for i in range(cantidad):
    digito = int(input(f"INGRESE EL {i+1} DIGITO: "))
    if digito < base:
      numero1.append(digito)
    else:
      while digito >ç base:
        digito = int(input(f"INGRESE EL {i+1} DIGITO: "))
for digito in numero1:
  for i in numero2:
    nuevo_digito = digito * [i]
    if nuevo_digito > base:
      while nuevo_digito / base > base
        nuevo_digito / base