# -*- coding: utf-8 -*-
"""herrera-jens-pc2-p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZGL6pJIILbU7Fp9zqybQjc0kWEKlubO
"""



n = int(input("Ingrese la cantidad de alumnos: "))
aprobados = 0
arreglo = [0]*n
for i in range(n):
  arreglo[i]=int(input(f"Nota del alumno {i+1}: "))
  if arreglo[i]>=10:
    aprobados += 1
porcentaje = (aprobados/n)*100
#print(arreglo)
for i in range(len(arreglo)):
  print(arreglo[i],end='  ')
#print(aprobados)
print(f"{round(porcentaje,2)}% de aprobados")
while porcentaje<70:
  aprobados=0
  for i in range(len(arreglo)):
    arreglo[i]+=1
    if arreglo[i]>=10:
      aprobados+=1
  porcentaje = (aprobados/n)*100
  #print(arreglo)
  for i in range(len(arreglo)):
    print(arreglo[i],end='  ')
  print(f"{round(porcentaje,2)}% de aprobados")
# 7  9  14  8  6  5  10  28.57% de aprobados