# -*- coding: utf-8 -*-
"""herrera-jens-ep-p3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RHspaLwtrvD6sTJxwybYDShrdiyTQYOG

Escriba un programa que gire sucesivamente 90° una matriz rectangular de M*N en sentido horario hasta volver a
la matriz original. Debe imprimir la matriz original y la matriz luego de cada giro
"""

matriz = []
g1=[]
g2=[]
g3=[]
M=int(input("Ingrese numero de filas: "))
N=int(input("Ingrese numero de columnas: "))
for i in range(M):
  matriz.append([0]*N)
#INSERTAR DATOS:
for i in range(M):
  for j in range(N):
    matriz[i][j]=int(input(f"matriz[{i}][{j}]: "))
print(matriz)
#matriz = [[1, 2, 3], [4, 5, 6]]
#GIRAR MATRIZ
for i in range(M):
  for j in range(N):
    g1[j][i]=matriz[i][j]  # g1[0][0] = matriz[1][0]; #g1[0][1]
print(g1)