# -*- coding: utf-8 -*-
"""herrera-jens-ep-p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEvq7Nqh_tufbolWC5XLbl57PdLxHR8_

Escriba un programa para leer en arreglos los datos de n alumnos, donde n<=30. Por cada alumno debe leer:
código (número de 2 cifras), peso y talla, luego debe mostrar los datos ordenados descendentemente por peso
y para los empates en peso mostrar ordenado ascendentemente por talla. Luego debe insertar los datos de un
nuevo estudiante de modo tal que se mantenga el ordenamiento. Ejemplo: Si n=6
"""

n=int(input("Ingrese numero de alumnos: "))
while n>30:
  n=int(input("Ingrese numero de alumnos: "))
matriz = []
indices=[]
ordenada = []
for i in range(n):
  matriz.append([0]*3)
for i in range(n):
  ordenada.append([0]*3)
#AGREGANDO DATOS:

for i in range(n):
  print(f"ESTUDIANTE {i+1}")
  matriz[i][0]= int(input("Ingrese el Código: "))
  while matriz[i][0]>=100:
    matriz[i][0]= int(input("Ingrese el Código: "))
  matriz[i][1]= float(input("Ingrese el Peso: "))
  matriz[i][2] = float(input("Ingrese la talla: ")) 
  indices.append(i) 

#ORDENARLOS DESCENDIENTEMENTE
for i in range(n-1):
  if matriz[i+1][1]>matriz[i][1]:
    aux = indices[i]
    indices[i]=indices[i+1]
    indices[i+1]=aux
    
for i in range(len(indices)):
  ordenada[indices[i]][0]=matriz[i][0]
  ordenada[indices[i]][1]=matriz[i][1]
  ordenada[indices[i]][2]=matriz[i][2]
 #  0                1               2                3                 4               5
#[[12, 60.6, 1.55],[29, 73.8, 1.82],[15, 82.4, 1.78],[31, 60.6, 1.71],[73, 73.8, 1.77],[62, 82.1, 1.91]]
#indices = [1, 2, 0, 4, 5, 3]
print(matriz)
print(ordenada)