# -*- coding: utf-8 -*-
"""herrera-jens-ep-p2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDLeSHBRzBnFKeIAJF2XlbAXm5xOfKR7
"""

n = int(input("Ingrese un número en base 10: "))
bases=[0,0,0,0,0,0,0,0]
capicuas = []
indc=[]
while n<=0:
  n = int(input("Ingrese un número en base 10: "))
# LISTA BASES
for b in range(2, 10):
  nb = 0
  aux = n   #aux=25
  exp = 0
  while aux!=0:   
    r=aux%b   #r=25%2=1
    nb += r*(10**(exp))   #nb= 
    aux = aux//b
    exp+=1
  bases[b-2]= nb

#          2       3   4    5    6   7   8  9
#bases = [11001, 221, 121, 100, 41, 34, 31, 27]
for b in range(8):
  nc=0
  aux=bases[b]  #aux=11001
  while aux!=0:
    r=aux%10  #r=1
    nc = 10*nc+ r
    aux = aux//10
  if nc==bases[b]:
    capicuas.append(nc)
    indc.append(b)
for i in range(len(indc)):
  print(f"El número es capicúa en la base: {indc[i]+2} (pues el número es {bases[indc[i]]})")