# -*- coding: utf-8 -*-
"""pregunta 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ixj-E3GOLKGgvV1Nx5LE4ytxlzMY4BwC
"""

#def rotar(matriz,n,k,capa):
    #for n in range(k):






matriz=[]
while True:
    n=int(input("Ingrese el orden de la matriz: "))
    if n>2 and n%2!=0:
      break
    else:
      print("EL ORDEN DE LA MATRIZ DEBE SER MAYOR A DOS E IMPAR")
for i in range(n):
  matriz.append([])
for i in range(n):
  for j in range(n):
    m=int(input(f"INGRESE EL VALOR {[i,j]}: "))
    matriz[i].append(m)
while True:
   capa=int(input("INGRESE LA CAPA A ROTAR: "))
   if 1<=capa<=n-1/2:
     break
   else:
     print(" INGRESE DE NUEVO LA CAPA ")
while True:
    k=int(input("INGRESE LAS VECES A ROTAR (1,2 o 3): "))
    if 1<k<=3:
      break
    else:
      print("SOLO PUEDE ROTAR 1, 2 o 3 VECES")
print("----ANTES DE LA ROTACION---")
for i in matriz:
  print(i)
#print(rotar(matriz,n,k,capa))