# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2EoI8ryZOdkVOOA1u3r94DVbWtnhykU
"""

b = int(input("Ingrese la base: "))
r =True
lista_1=[]
lista_2=[]
contador=0
cont_1=0
while r==True:
  numero=int(input(f"Ingrese el primer numero en base {b}: "))
  aux = numero
  contador=0
  while numero>0:
    residuo=numero%10
    numero=numero//10
    if residuo>=b:
      print("Numero incorrecto")
      contador=1
      break
  if contador==0:
    r=False
    print("Numero aceptado")
while aux>0:
    residuo=aux%10
    aux=aux//10
    lista_1.append(residuo)
    cont_1=cont_1+1
lista_3=[0]*cont_1
for i in range(cont_1):
  lista_3[i]= lista_1[cont_1-1-i]
r=True
contador=0
cont_1=0
while r==True:
  numero=int(input(f"Ingrese el segundo numero en base {b}: "))
  aux = numero
  contador=0
  while numero>0:
    residuo=numero%10
    numero=numero//10
    if residuo>=b:
      print("Numero incorrecto")
      contador=1
      break
  if contador==0:
    r=False
    print("Numero aceptado")
while aux>0:
    residuo=aux%10
    aux=aux//10
    lista_2.append(residuo)
    cont_1=cont_1+1
lista_4=[0]*cont_1
for i in range(cont_1):
  lista_4[i]= lista_2[cont_1-1-i]
print(f"Primer numero en base b {lista_3}")
print(f"Segundo numero en base b {lista_4}")

