# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2EoI8ryZOdkVOOA1u3r94DVbWtnhykU
"""

n = int(input("Ingrese la cantidad de notas: "))
notas = [0]*n
suma=0
aprobados = 0
porcentaje =0.00
r=True
for i in range(n):
  x= int(input(f"Ingrese la nota {i+1}: "))
  notas[i]=x
  if x >=10:
    aprobados = aprobados + 1
porcentaje = (aprobados/n)*100
while r==True:
  if porcentaje<=70:
    print(f"{notas} {porcentaje}% de aprobados")
    aprobados=0
    for i in range(n):
      if notas[i]<20:
        a = notas[i]+1
        notas[i]= a
        if a>=10:
          aprobados = aprobados+1
      elif notas[i]==20:
        aprobados = aprobados+1
    porcentaje=(aprobados/n)*100
  else:
    r=False
print(f"{notas} {porcentaje}% de aprobados")